### PR TITLE
fix hovering issue with popup

### PR DESCRIPTION
**Pull request by amelted**
its self explanatory that popup thing was so annoying that i wouldnt be able to live with myself without fixing it 
image

### CODE REVIEW

**Comment by amelted** [comment]
this fixes issue #80

**Comment by marcelstoer** [comment]
Thanks for the contribution! Did you fix any of the Py dependencies to make it work (i.e. bump them)?

**Comment by amelted** [comment]
I did for my specific machine, I believe I used PyInstaller==6.0 (had to remove --windowed build argument) and WxPython==4.2.1 to make it work for Python 3.12.4

**Comment by marcelstoer** [comment]
Can I ask you to please rebase and include those changes in this PR (requirements.txt and the build files).

**Comment by amelted** [comment]
idk if i did that right im still learning git

**Comment by amelted** [comment]
> Can I ask you to please rebase and include those changes in this PR (requirements.txt and the build files).

Just wondering if you saw that I added these

**Comment by HHHartmann** [comment]
You would still need to rebase to the master branch, so it can be merged there.

**Comment by amelted** [comment]
im stupid can you explain that i might maybe should redo this pr lol

**Comment by amelted** [comment]
i try again

**Comment by marcelstoer** [comment]
@amelted don't worry about it. I'll sort it out and give you proper credit. However, I need to fold this into a general dependency upgrade (it's been long overdue).

**Comment by marcelstoer** [comment]
I merged it into the [`pop-up-fix`](https://github.com/marcelstoer/nodemcu-pyflasher/tree/pop-up-fix) branch. Now I'm ironing out the code style issues and I wonder what `wx.EVT_` event we should bind to. `wx.EVT_MOTION` does indeed solve the problem but you can't click the links in the panel anymore because the panel disappears immediately.

**Pull request merged**
